version: "3.9"
services:
  # redisearch first
  redisearch:
    image: "redis/redis-stack-server:latest"
    network_mode: "host"
  # app connects to redisearch
  api:
    depends_on:
      - redisearch
    build:
      context: .
      dockerfile: GoApi.Dockerfile
    network_mode: "host"
    # python script loads the data
  data:
    depends_on:
      - redisearch
    build:
      context: .
      dockerfile: LoadMessyData.dockerfile
    network_mode: "host"
